"""usr2

Revision ID: b97b90ef88fb
Revises: e16da7cf9b1d
Create Date: 2022-07-08 13:23:30.416040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97b90ef88fb'
down_revision = 'e16da7cf9b1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
