"""usr

Revision ID: e16da7cf9b1d
Revises: 2d00eeca7712
Create Date: 2022-07-08 13:04:56.351985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16da7cf9b1d'
down_revision = '2d00eeca7712'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
